# Generated by Django 5.0.6 on 2024-06-26 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
